# Generated by Django 4.2.7 on 2023-12-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookmodel_categories'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='books.bookmodel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[(1, 'Deposit'), (2, 'Return'), (3, 'Borrow')], max_length=20),
        ),
    ]
