# Generated by Django 4.2.7 on 2023-12-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactionmodel_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='borrow_return_date',
        ),
    ]
