# Generated by Django 4.2.7 on 2023-12-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='borrowing_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
