# Generated by Django 4.2.7 on 2023-12-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookmodel_borrowing_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='books.categorymodel'),
        ),
    ]
