# Generated by Django 4.2.7 on 2023-12-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_categorymodel_bookmodel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='books.categorymodel'),
        ),
    ]
