# Generated by Django 4.2.7 on 2023-12-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookmodel_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='timestamps',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
