# Generated by Django 4.2.7 on 2023-12-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
