# Generated by Django 4.2.7 on 2023-12-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customermodel_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phone_no',
            field=models.CharField(max_length=100),
        ),
    ]
